### ISSUE TITLE
jmonkeyvr not working with osvr openvr emulator

### ISSUE THREAD

**Issue by vt5491** [phr00t/jmonkeyengine-virtual-reality#2]
Because oculus driver 0.8 for DK2 will not run on laptops (no nvidia class "m" gpus allowed), I've been using the [OSVR](http://osvr.github.io/) HDK 1.3 for my VR development until I can upgrade to an Oculus-ready system.

I'm currently evaluating using jMonkeyEngine as my VR development platform (the other contenders are Unity and WebVR/three.js).   [OSVR on unity](https://osvr.github.io/build-with/) was a relative breeze to setup with OSVR.  While it's certainly not turnkey, compared to  [the problems I've had with WebVR](https://github.com/toji/chrome-webvr-issues/issues/52), and now jMonkeyVR, I now realize how easy it was.

A little background:  OSVR is basically a competitor to OpenVR.  They have a special emulation driver that   [allows your OSVR HDK13 HMD to present itself as an OpenVR](https://github.com/OSVR/SteamVR-OSVR)  device (eg a HTC Vive).  Basically this just means you add a binary to your steamVR directory:

![image](https://cloud.githubusercontent.com/assets/8662470/13839333/6586706c-ebd7-11e5-923a-a9dd87433cf6.png)

Asides from a dearth of documentation, it basically works -- you can run the steamvr demo app _hellovr_sdl.exe_ out the box, and using [special chrome builds](https://drive.google.com/folderview?id=0BzudLt22BqGRbW9WTHMtOWMzNjQ#list) that map webVR into openVR (which in turn maps to OSVR) you can get it work under a browser, and invoke the Three.js API.

So that brings up jMonkeyVr.  I've followed all the setups on this site, but when I try to build the [TestOpenVR app](https://github.com/phr00t/jMonkeyVR/blob/master/test/jmevr/TestOpenVR.java) under jMonkeySDK I get _Invalid Memory Access_:

```
[run:
[OSVR] Connecting to default (local) host
[OSVR] Client context initialized for com.osvr.SteamVR
[OSVR] Got connection to main OSVR server
[OSVR] Got updated path tree, processing
[OSVR] Connected 0 of 0 unconnected paths successfully
[OSVR] Connection process took 47ms: have connection to server, have path tree
[OSVR] Interface initialized for /me/head
[OSVR] Constructed a TrackerHandler for com_osvr_Multiserver/OSVRHackerDevKitPrediction0@localhost sensor 0
[OSVR] Successfully produced handler for /me/head
[OSVR] Interface initialized for /me/head
[OSVR] Interface initialized for /me/head
[OSVR] Display: OSVR HDK (Version 1.2) [Display descriptor note: Suitable for HDK 1.0-1.2]
[OSVR] Created an OSVR_DisplayConfigObject!
[OSVR] Interface initialized for /me/head
OpenVR initialized & VR connected.
Mar 16, 2016 11:46:36 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.1-alpha1
 * Branch: master
 * Git Hash: c5c893f
 * Build Date: 2015-08-17
OpenVR Compositor initialized OK.
initTestScene:Thread[jME3 Main,5,main]
Mar 16, 2016 11:46:38 PM com.jme3.app.Application handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.Error: Invalid memory access
    at com.sun.jna.Native.invokeInt(Native Method)
    at com.sun.jna.Function.invoke(Function.java:390)
    at com.sun.jna.Function.invoke(Function.java:323)
    at com.sun.jna.Function.invoke(Function.java:275)
    at com.sun.jna.CallbackReference$NativeFunctionHandler.invoke(CallbackReference.java:646)
    at com.sun.proxy.$Proxy59.apply(Unknown Source)
    at jmevr.util.OpenVRViewManager.sendTextures(OpenVRViewManager.java:152)
    at jmevr.app.VRApplication.update(VRApplication.java:558)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:152)
    at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:192)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:233)
    at java.lang.Thread.run(Thread.java:745)

[OSVR] OSVR_DisplayConfigObject destructor
[OSVR] Client context shut down for com.osvr.SteamVR
Using breakpad crash handler
Setting breakpad minidump AppID = 250820
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
BUILD SUCCESSFUL (total time: 3 seconds)
]
```

and just in case you think it's an enviromental issue, I ponied up a whole $2.99 and bought a copy of _Sperminator_ and it has the same problem:

```
$ ./Spermination.exe

Vince@hp_laptop_envy  /c/Program Files (x86)/Steam/steamapps/common/Spermination
$ OpenVR initialized & VR connected.
Found JAR location: C:\Program Files (x86)\Steam\steamapps\common\Spermination
Mar 16, 2016 11:50:11 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Mar 16, 2016 11:50:11 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.1-5774
 * Branch: master
 * Git Hash: 899b7a8
 * Build Date: 2016-03-10
Mar 16, 2016 11:50:11 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 3 context running on thread main
 * Graphics Adapter: GLFW 3.2.0 Win32 WGL VisualC DLL
Mar 16, 2016 11:50:11 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: Intel
 * Renderer: Intel(R) HD Graphics 4000
 * OpenGL Version: 4.0.0 - Build 10.18.10.4276
 * GLSL Version: 4.00 - Build 10.18.10.4276
 * Profile: Compatibility
Mar 16, 2016 11:50:11 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.ogre.MeshLoader
Mar 16, 2016 11:50:11 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.ogre.SkeletonLoader
Mar 16, 2016 11:50:11 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.ogre.MaterialLoader
Mar 16, 2016 11:50:11 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.ogre.SceneLoader
Mar 16, 2016 11:50:11 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.blender.BlenderModelLoader
Mar 16, 2016 11:50:11 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.fbx.SceneLoader
Mar 16, 2016 11:50:11 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.fbx.SceneWithAnimationLoader
Mar 16, 2016 11:50:11 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.17.2
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFTX_device_clock ALC_SOFT_HRTF ALC_SOFT_loopback ALC_SOFT_pause_device
 * AL extensions: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length
Mar 16, 2016 11:50:11 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio effect extension version: 1.0
Mar 16, 2016 11:50:11 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4
OpenVR Compositor initialized OK.
*** Error! ***

First thing to do is verify your Java installation. Install the latest from http://java.com/getjava
and make sure to uninstall old versions.

If still having trouble, check the game's forum for help & report this: I'd love to get this addressed!

Thread: main, Version: v1.26

java.lang.Error: Invalid memory access
        at com.sun.jna.Native.invokeInt(Native Method)
        at com.sun.jna.Function.invoke(Function.java:390)
        at com.sun.jna.Function.invoke(Function.java:323)
        at com.sun.jna.Function.invoke(Function.java:275)
        at com.sun.jna.CallbackReference$NativeFunctionHandler.invoke(CallbackReference.java:646)
        at com.sun.proxy.$Proxy59.apply(Unknown Source)
        at jmevr.util.OpenVRViewManager.sendTextures(OpenVRViewManager.java:159)
        at jmevr.app.VRApplication.update(VRApplication.java:588)
        at com.jme3.system.lwjgl.LwjglWindow.runLoop(LwjglWindow.java:372)
        at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:456)
        at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:299)
        at com.jme3.app.Application.start(Application.java:446)
        at jmevr.app.VRApplication.start(VRApplication.java:310)
        at Init.Main.main(Main.java:137)


******
AL lib: (EE) alc_cleanup: 1 device not closed
Setting breakpad minidump AppID = 363460
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198289258901 [API loaded no]


```

Note how it says "Intel 4000", which is my internal video card.  I've also started it from the File Explorer specifiying "use nvidia driver", and I still get the problem, so I don't think this is related to the problem.

I tried all the basic tweaking: running the 32-bit and 64-bit versions of the OSVR server, trying various sample configs, putting the monitor into duplicated and extended mode to no avail.

I mentioned all the background of this problem, because it may indeed turn out to be a problem with the OSVR _openVR_ emulator itself i.e. it's kind of cross-domain problem.  But I'd figure I'd just throw it out there to see if you can make any recommendations.

Many Thanks.

**Comment by vt5491** [comment]
Windows 10
jMonkeyEngine SDK 3.1-alpha1, with Phr00t's jMonkeyEngine build overlaid on projects dist/lib
Nvidia 650M, 364.51
HP Envy DV7, 16GB

**Comment by phr00t** [comment]
Try configuring Java (any version that might be used) to use the NVidia chipset. The EXE is just a stub and it might not translate the "use nvidia" option correctly.

**Comment by vt5491** [comment]
Well, we're moving in the right direction at least.  After enabling 'java', 'javaw', and 'javaws' under jre, jdk, and the indirection pointers under "C:/ProgramData/Oracle" to use the gpu by default (probably overkill, as I think you only needed to update the jre binaries), and starting Spermination with "use high-performance nvidia" (I also added the Spermination.exe to the gpu list, but I still have to start it with the "use high-performance" right-click option for some reason), I was able to get split scene mode with head tracking i.e. you're classic VR profile!

Unfortunately, it's on my laptop screen only and not on the HMD, even when I am in "Duplicate" mode.  I also have no keyboard input, or mouse, and have to ctrl-alt-del to bring up the task manager to kill the process.

My project, after I relaunched the SDK to run with nvidia, is also no longer getting the "invalid memory", but dying with the following:

```
initTestScene:Thread[jME3 Main,5,main]
Mar 17, 2016 1:57:39 PM com.jme3.app.Application handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.renderer.RendererException: compile error in: ShaderSource[name=jmevr/shaders/Unshaded.frag, defines, type=Fragment, language=GLSL150]
0(4) : error C7101: Macro FRAGMENT_SHADER redefined

    at com.jme3.renderer.opengl.GLRenderer.updateShaderSourceData(GLRenderer.java:1126)
    at com.jme3.renderer.opengl.GLRenderer.updateShaderData(GLRenderer.java:1153)
    at com.jme3.renderer.opengl.GLRenderer.setShader(GLRenderer.java:1217)
    at com.jme3.material.Material.render(Material.java:1215)
    at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:568)
    at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:266)
    at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:305)
    at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:803)
    at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:731)
    at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1030)
    at com.jme3.renderer.RenderManager.render(RenderManager.java:1070)
    at jmevr.app.VRApplication.update(VRApplication.java:552)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:152)
    at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:192)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:233)
    at java.lang.Thread.run(Thread.java:745)
```

Hopefully, I can just comment out some more code to try to get around that (I've had to comment out a lot of code to get past all the previous errors I've had)

Now, with Spermination at least, I'm just in the classic "VR Hell" of trying to find just the right settings to get it to display on the HMD, going back and forth between direct and extended mode etc.  

Is there a way I can force sperimation to come up windowed so I can drag it over to the second extended display?  And also, will spermination go into split-screen if it's not running fullscreen?

So thank you for your suggestion.  I got past the first hurdle, and it was very important to know that I can at least get split-screen and head tracking.  Of course, right now I've somehow lost the ability to get even that ..too many tweaks I think.  But it really helps to know I got it working at least once.

I will keep you posted with my results.

**Comment by jherico** [comment]
>  Is there a way I can force sperimation to come up windowed so I can drag
> it over to the second extended display? And also, will spermination go into
> split-screen if it's not running fullscreen?

Run the OSVR display as a second X11 screen, and set the DISPLAY variable
to target that screen.  See this page:
https://codelab.wordpress.com/2015/04/02/proper-oculus-rift-dk2-setup-on-gnulinux/

**Comment by vt5491** [comment]
I got the game to show on the HMD, with split screen and head-tracking.  

For anyone out there using OSVR, you need to do the following (Windows):

1) Be in extended mode on your displays (e.g. two displays)
2) start up the osvr_server.exe with no parameters (which will use the default config file 'osvr_server_config.json' which is in the same directory as 'osvr_server.exe' and _not_ under the 'sample-configs' directory.

I used the 64-bit version of the server, but I think the 32-bit should work too.  

I experimented with the following files in sample-configs:
osvr_server_config.HDK13DirectMode.sample.json 
osvr_server_config.HDK13ExtendedLandscape.sample.json
osvr_server_config.renderManager.sample.json
renderManager.direct.landscape.json
renderManager.extended.landscape.json

and I tried them with "duplicate" mode (one screen), and "extended" mode.  The combination of the default config file and extended mode is the only one that worked fully.  Some of the others came close, but the display would show on the laptop monitor only and not the HMD.

Unfortunately, I still have no keyboard or mouse input so the game is effectively not playable.  Regarding this, I can't think of any configuration things to do to fix this.

My next target is to get my project to also run, and since I will have control over the code, hopefully I'll be able to address the keyboard issue as well.

But between enabling everything to force use the nvidia processor, and finding the right mix of config files, and display modes, I am able to at least get the full head tracking experince on the HMD!

Unfortunately, the suggestion from jherico won't work for me since I'm running windows.  But thank you for the info anyway.  Fortunately, I did not have to resort to manually moving it to a second display anyway.

**Comment by vt5491** [comment]
I just [found this link](http://www.gameplanet.com.au/videos/g56d4b7a78a01f/Spermination-OSVR-SteamVR-integration-trailer/) which shows spermination being played on an OSVR HDK1.3 -- with full input control to boot.

So I must still be doing something wrong...

**Comment by vt5491** [comment]
Ok, I got my app to work now too.  I just started with the basic JME game app, but this time I figured out how to properly use the libraries from phroot's JME build (I was previously just overlaying the dist folder of my project with the new libraries, until I figured out I need to delete the old libs and and add the new libs _within_ the project -- kind of obvious now that I'm a little more familiar with the environment).

But I still can't get keyboard input to work.  When I run my app as _SimpleApplication_ , the esc ends the app.  I don't see anywhere in the main class where this is directly handled, so it must be built into JME somehow.  But when I run my app as _VRApplication_ then esc no longer works.

I notice that when the VR app runs, there are two windows.  One is the primary screen and is just a black window with the title "JMonkeyEngine Window".  Then in my secondary display there's a fullscreen window called "VRCompositor HeadSet Window".  My guess is that this second window is simply not getting keyboard focus.  I try to click on it and put the cursor over it but this has no effect.  The problem is if I kill the app by closing the JME window, or by killing the java process, I have to unplug and re-plugin the power supply (e.g power-cycle) my HMD in order to reset it.  This is not hard, but it takes about 5-10 seconds, and is rather tedious.

My basic question is: is there anything special I need to do to get keyboard focus when running in VR mode?  Or do I really just need to spend some more time learning about jMonkey, and stop asking so many questions?

**Comment by phr00t** [comment]
The application window ("JMonkeyEngine Window") needs to have focus to receive input. The "VR Compositor HeadSet Window" is what is being sent to the headset & gets created by SteamVR. If that window (or any other) has focus, no input will be processed.

**Comment by vt5491** [comment]
Ok, that's a good distinction to know.  I obviously did try clicking on both windows and giving them focus.  Hell, I clicked everywhere..the desktop, the toolbar etc.  Maybe I just have to programmatically give my app focus?  Maybe the osvr "thread" somehow "steals" the focus?  I will investigate this situation further.  

If you don't mind me asking, what was your environment when developing _spermination_?  Was it an oculus rift?  HTC Vive?  Have you ever tested or known anyone who's used an Osvr?

**Comment by neph1** [comment]
@vt5491 
Would you care to do a post of your findings on "jMonkeyVR and OSVR" over at: http://hub.jmonkeyengine.org/c/user-code-projects/virtual-reality ? Especially the stuff on how you got it working. It'd be a good reference for me and others as it might get lost here on github. 
Thanks

**Comment by vt5491** [comment]
Thanks for the encouragement.  It's always nice to know there are people out there who may be interested in what you've learned.   I certainly wish I could go back in time and tell myself all the things to look out for etc.  

I will endeavor to do a more detailed post to the forum -- especially if I can figure out how to get over this damned input problem.
.

**Comment by vt5491** [comment]
Keyboard input is now working!

Really, it was just as simple as adding keyboard listeners in the code.  Here's a snippet of the code, borrowed liberally from the "TestOpenVr.java" file in the repo:

```
...
        //vt add
        this.initInputs();
        observer = new Node("observer");

        observer.setLocalTranslation(new Vector3f(8.0f, 0.0f, 0.0f));

        VRApplication.setObserver(observer);
        rootNode.attachChild(observer);
        //vt end
    }

    //vt add
    private void initInputs() {
        System.out.println("InitInput: entered");
        inputManager.addMapping("forward", new KeyTrigger(KeyInput.KEY_W));
        inputManager.addMapping("backward", new KeyTrigger(KeyInput.KEY_S));

        inputManager.addMapping("exit", new KeyTrigger(KeyInput.KEY_ESCAPE));

        ActionListener acl = new ActionListener() {
            public void onAction(String name, boolean keyPressed, float tpf) {
                if(name.equals("forward")){
                    System.out.println("initInput: forward key pressed");
                    observer.move(VRApplication.getFinalObserverRotation().getRotationColumn(2).mult(1f));
                }
                else if(name.equals("backward")){
                    System.out.println("initInput: backward key pressed");
                    observer.move(VRApplication.getFinalObserverRotation().getRotationColumn(2).mult(-1f));
//                        moveForward = false;
                }
                else if (name.equals("exit")) {
                    System.out.println("initInput: exit key pressed");
                    System.out.println("initInput: now exiting");
                    System.exit(0);
                }
            }
        };

        inputManager.addListener(acl, "forward");
        inputManager.addListener(acl, "backward");
        inputManager.addListener(acl, "exit");
    }    
    //vt end

```

You just cannot rely on the built-in ESC key handler -- you have to code one up yourself.  

And I still cannot explain why the keyboard events for _Spermination_ do not work.  It's possible it just doesn't accept WASD keys, but I'm pretty sure I was able to use the keys when it was running in standard windowed mode.  And besides, the mouse wasn't working either.  I'll give it another try after I'm a little more comfortable writing my own app.

So I guess the whole situation about no keyboard input (at least for my project) was just a red herring.  I now have a fully function spinning cube app.  And since I'm getting a clean exit, I don't have to power-cycle my HMD each time.  So now I'm really happy, and can seriously begin to evaluate jMonkeyEngine and jMonkeyVr.

Great work guys.

p.s I'll try to move any further threads of this sort over to the jMonkeyEngine forum.  None of the problems I had along the way appear to have been caused by jMonkeyVr anyway.
