### ISSUE TITLE
Please provide a clearer startup guide.

### ISSUE THREAD

**Issue by i-make-robots** [phr00t/jmonkeyengine-virtual-reality#5]
I don't understand the startup instructions.  I will continue to muddle.  Assistance would be greatly appreciated.

**Comment by i-make-robots** [comment]
Got jMonkeyEngine SDK started.  Appears to be it's own IDE?  I guess Eclipse wasn't good enough.
Removed all jme3-ljgwl libraries and added 
Added JMonkeyVR/JMonkeyVR.jar and JMonkeyVR/jna-4.2.1.jar to the libraries.
Created library jme3-lwjgl3 from 

jmonkeyengine\jme3-core\src\main\java\com\jme3\app exists and jme3-core is an included library BUT VRApplication says com.jme3.\* does not exist.

Running produces "please make sure jme3-lwjgl is in the library path."  Added them back in.

Now I get 

May 30, 2016 3:53:26 PM jmevr.app.VRApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.NoSuchFieldError: _VRInstancing_RightCamProjection
    at jmevr.util.OpenVRViewManager.setupCamerasAndViews(OpenVRViewManager.java:441)
    at jmevr.util.OpenVRViewManager.initialize(OpenVRViewManager.java:179)
    at jmevr.app.VRApplication.initialize(VRApplication.java:1065)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
    at java.lang.Thread.run(Thread.java:745)

Which is the error I saw running the precompiled demo.  What next, please?

**Comment by i-make-robots** [comment]
With instancing off,

May 30, 2016 5:12:39 PM jmevr.app.VRApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.NoClassDefFoundError: com/jme3/input/lwjgl/GlfwMouseInput
    at jmevr.util.VRMouseManager.init(VRMouseManager.java:48)
    at jmevr.util.OpenVRViewManager.initialize(OpenVRViewManager.java:183)
    at jmevr.app.VRApplication.initialize(VRApplication.java:1065)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.jme3.input.lwjgl.GlfwMouseInput
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 6 more

**Comment by phr00t** [comment]
Sounds like you overlooked these two important lines:

#1 "Phr00t's jMonkeyEngine build is required: https://github.com/phr00t/jmonkeyengine (the main jME3 build might work, but VR-specific changes will be made first on Phr00t's build) -- you can just use the JAR/libs under the dist/ and lib/ folders"

#2 Use jme3-lwjgl3 in your project, not jme3-lwjgl (needs GLFW in LWJGL 3).

You don't need to create jme3-lwjgl3, it is right here:

https://github.com/phr00t/jmonkeyengine/blob/master/dist/lib/jme3-lwjgl3.jar

**Comment by i-make-robots** [comment]
I read the readme carefully and didn't understand it.  My notes in this
issue were a stream-of-conciousness as I muddled through it.
The pro-tip about ussing lwjgl3 didn't say where it was located, and my
intuition led me to the wrong files.
Whoops!

On Tue, May 31, 2016 at 5:45 AM, Phr00t notifications@github.com wrote:

> Sounds like you overlooked these two important lines:
> 
> #1 https://github.com/phr00t/jMonkeyVR/issues/1 "Phr00t's jMonkeyEngine
> build is required: https://github.com/phr00t/jmonkeyengine (the main jME3
> build might work, but VR-specific changes will be made first on Phr00t's
> build) -- you can just use the JAR/libs under the dist/ and lib/ folders"
> 
> #2 https://github.com/phr00t/jMonkeyVR/issues/2 Use jme3-lwjgl3 in your
> project, not jme3-lwjgl (needs GLFW in LWJGL 3).
> 
> You don't need to create jme3-lwjgl3, it is right here:
> 
> https://github.com/phr00t/jmonkeyengine/blob/master/dist/lib/jme3-lwjgl3.jar
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/phr00t/jMonkeyVR/issues/5#issuecomment-222677307, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABZYhmPvRyUI9LQ4ch8IxLKegALyfnrSks5qHC1VgaJpZM4IqCrM
> .

## 

Dan Royer, Owner, Marginally Clever Robots
https://www.marginallyclever.com/
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by i-make-robots** [comment]
removed jme3-lwjgl\* libraries from project.
added jar /dist/lib/jme3-lwjgl3.jar

on run,

May 31, 2016 9:17:34 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.1-beta1
- Branch: HEAD
- Git Hash: 310f4db
- Build Date: 2016-04-25
  Exception in thread "main" java.lang.NoClassDefFoundError:
  org/lwjgl/opengl/GLDebugMessageARBCallbackI
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:264)
  at
  com.jme3.system.JmeDesktopSystem.newContextLwjgl(JmeDesktopSystem.java:199)
  at
  com.jme3.system.JmeDesktopSystem.newContext(JmeDesktopSystem.java:279)
  at com.jme3.system.JmeSystem.newContext(JmeSystem.java:162)
  at jmevr.app.VRApplication.start(VRApplication.java:607)
  at jmevr.app.VRApplication.start(VRApplication.java:584)
  at mygame.Main.main(Main.java:47)
  Caused by: java.lang.ClassNotFoundException:
  org.lwjgl.opengl.GLDebugMessageARBCallbackI
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 8 more
  Using breakpad crash handler
  Setting breakpad minidump AppID = 250820
  Forcing breakpad minidump interfaces to load
  Looking up breakpad interfaces from steamclient
  Calling BreakpadMiniDumpSystemInit

On Tue, May 31, 2016 at 9:14 AM, Dan Royer dan@marginallyclever.com wrote:

> I read the readme carefully and didn't understand it.  My notes in this
> issue were a stream-of-conciousness as I muddled through it.
> The pro-tip about ussing lwjgl3 didn't say where it was located, and my
> intuition led me to the wrong files.
> Whoops!
> 
> On Tue, May 31, 2016 at 5:45 AM, Phr00t notifications@github.com wrote:
> 
> > Sounds like you overlooked these two important lines:
> > 
> > #1 https://github.com/phr00t/jMonkeyVR/issues/1 "Phr00t's
> > jMonkeyEngine build is required: https://github.com/phr00t/jmonkeyengine
> > (the main jME3 build might work, but VR-specific changes will be made first
> > on Phr00t's build) -- you can just use the JAR/libs under the dist/ and
> > lib/ folders"
> > 
> > #2 https://github.com/phr00t/jMonkeyVR/issues/2 Use jme3-lwjgl3 in
> > your project, not jme3-lwjgl (needs GLFW in LWJGL 3).
> > 
> > You don't need to create jme3-lwjgl3, it is right here:
> > 
> > https://github.com/phr00t/jmonkeyengine/blob/master/dist/lib/jme3-lwjgl3.jar
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/phr00t/jMonkeyVR/issues/5#issuecomment-222677307,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/ABZYhmPvRyUI9LQ4ch8IxLKegALyfnrSks5qHC1VgaJpZM4IqCrM
> > .
> 
> ## 
> 
> Dan Royer, Owner, Marginally Clever Robots
> https://www.marginallyclever.com/
> Ph: +1 (604) 259-9564
> Mo: +1 (604) 916-2281

## 

Dan Royer, Owner, Marginally Clever Robots
https://www.marginallyclever.com/
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by phr00t** [comment]
What libraries do you have added? You must still be missing something, somewhere. You probably are missing the lwjgl-3.0.0\* ones here:

https://github.com/phr00t/jmonkeyengine/tree/master/dist/lib

**Comment by i-make-robots** [comment]
I added those two libs.  Here's the current list:
http://imgur.com/g0IEBrm

Now I get:

OpenVR initialized & VR connected.
May 31, 2016 9:26:20 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.1-beta1
- Branch: HEAD
- Git Hash: 310f4db
- Build Date: 2016-04-25
  May 31, 2016 9:26:20 AM com.jme3.system.lwjgl.LwjglContext
  printContextInitInfo
  INFO: LWJGL 3 context running on thread main
- Graphics Adapter: GLFW 3.2.0 Win32 WGL VisualC DLL
  May 31, 2016 9:26:21 AM com.jme3.renderer.opengl.GLRenderer
  loadCapabilitiesCommon
  INFO: OpenGL Renderer Information
- Vendor: NVIDIA Corporation
- Renderer: GeForce GTX 960/PCIe/SSE2
- OpenGL Version: 4.5.0 NVIDIA 368.22
- GLSL Version: 4.50 NVIDIA
- Profile: Compatibility
  May 31, 2016 9:26:21 AM com.jme3.asset.AssetConfig loadText
  WARNING: Cannot find loader
  com.jme3.scene.plugins.blender.BlenderModelLoader
  May 31, 2016 9:26:21 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
  INFO: Audio Renderer Information
- Device: OpenAL Soft
- Vendor: OpenAL Community
- Renderer: OpenAL Soft
- Version: 1.1 ALSOFT 1.17.2
- Supported channels: 64
- ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT
  ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX
  ALC_EXT_thread_local_context ALC_SOFTX_device_clock ALC_SOFT_HRTF
  ALC_SOFT_loopback ALC_SOFT_pause_device
- AL extensions: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE
  AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE
  AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS
  AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic
  AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data
  AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points
  AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length
  May 31, 2016 9:26:21 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
  INFO: Audio effect extension version: 1.0
  May 31, 2016 9:26:21 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
  INFO: Audio max auxiliary sends: 4
  OpenVR Compositor initialized OK.
  <--- VR Initialization Information --->
  camLeft: Camera[location=(0.034849998, 0.0, 9.985)
  , direction=(0.0, 0.0, -1.0)
  res=1512x1680, parallel=false
  near=1.0, far=1000.0]
  camRight: Camera[location=(0.034849998, 0.0, 9.985)
  , direction=(0.0, 0.0, -1.0)
  res=1512x1680, parallel=false
  near=1.0, far=1000.0]
  <--- ----------------------------- --->
  May 31, 2016 9:26:23 AM com.jme3.renderer.opengl.GLRenderer
  updateShaderSourceData
  WARNING: Bad compile of:
  1    #version 150 core
  2    #define FRAGMENT_SHADER 1
  3    #define FRAGMENT_SHADER
  4    // -- begin import Common/ShaderLib/GLSLCompat.glsllib --
  5    #if defined GL_ES
  6    #  define hfloat highp float
  7    #  define hvec2  highp vec2
  8    #  define hvec3  highp vec3
  9    #  define hvec4  highp vec4
  10    #  define lfloat lowp float
  11    #  define lvec2 lowp vec2
  12    #  define lvec3 lowp vec3
  13    #  define lvec4 lowp vec4
  14    #else
  15    #  define hfloat float
  16    #  define hvec2  vec2
  17    #  define hvec3  vec3
  18    #  define hvec4  vec4
  19    #  define lfloat float
  20    #  define lvec2  vec2
  21    #  define lvec3  vec3
  22    #  define lvec4  vec4
  23    #endif
  24
  25    #if **VERSION** >= 130
  26    out vec4 outFragColor;
  27    #  define texture1D texture
  28    #  define texture2D texture
  29    #  define texture3D texture
  30    #  define texture2DLod texture
  31    #  if defined VERTEX_SHADER
  32    #    define varying out
  33    #    define attribute in
  34    #  elif defined FRAGMENT_SHADER
  35    #    define varying in
  36    #    define gl_FragColor outFragColor
  37    #  endif
  38    #endif
  39    // -- end import Common/ShaderLib/GLSLCompat.glsllib --
  40
  41    uniform sampler2D m_ColorMap;
  42
  43    in vec2 texCoord1;
  44
  45    out vec4 outColor;
  46
  47    void main(){
  48        outColor = texture2D(m_ColorMap, texCoord1);
  49        outColor.a *= 12.0 / (1.0 + outColor.a \* 11.0 );
  50    }

May 31, 2016 9:26:23 AM jmevr.app.VRApplication handleError
SEVERE: Uncaught exception thrown in Thread[main,5,main]
com.jme3.renderer.RendererException: compile error in:
ShaderSource[name=jmevr/shaders/GuiOverlay15.frag, defines, type=Fragment,
language=GLSL150]
0(3) : error C7101: Macro FRAGMENT_SHADER redefined

```
at
```

com.jme3.renderer.opengl.GLRenderer.updateShaderSourceData(GLRenderer.java:1200)
    at
com.jme3.renderer.opengl.GLRenderer.updateShaderData(GLRenderer.java:1227)
    at com.jme3.renderer.opengl.GLRenderer.setShader(GLRenderer.java:1291)
    at
com.jme3.material.logic.DefaultTechniqueDefLogic.render(DefaultTechniqueDefLogic.java:94)
    at com.jme3.material.Technique.render(Technique.java:167)
    at com.jme3.material.Material.render(Material.java:966)
    at
com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:616)
    at
com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:266)
    at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:314)
    at
com.jme3.renderer.RenderManager.renderTranslucentQueue(RenderManager.java:926)
    at
com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1106)
    at com.jme3.renderer.RenderManager.render(RenderManager.java:1137)
    at jmevr.app.VRApplication.update(VRApplication.java:895)
    at com.jme3.system.lwjgl.LwjglWindow.runLoop(LwjglWindow.java:370)
    at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:454)
    at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:297)
    at jmevr.app.VRApplication.start(VRApplication.java:609)
    at jmevr.app.VRApplication.start(VRApplication.java:584)
    at mygame.Main.main(Main.java:47)

Using breakpad crash handler
Setting breakpad minidump AppID = 250820
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit

On Tue, May 31, 2016 at 9:22 AM, Phr00t notifications@github.com wrote:

> What libraries do you have added? You must still be missing something,
> somewhere. You probably are missing the lwjgl-3.0.0\* ones here:
> 
> https://github.com/phr00t/jmonkeyengine/tree/master/dist/lib
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/phr00t/jMonkeyVR/issues/5#issuecomment-222741785, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABZYhrHkVxqogbB2Qi0N6X0sowriLY93ks5qHGBOgaJpZM4IqCrM
> .

## 

Dan Royer, Owner, Marginally Clever Robots
https://www.marginallyclever.com/
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by phr00t** [comment]
Remove all of the original jme3 libraries (the ones with stacked book icons) & _only_ use my JARs from dist/lib. You are trying to mix standard jme3 libraries with mine, which is likely to cause problems.

**Comment by i-make-robots** [comment]
Aha!  Now it runs.  Thank you for your patience and understanding.
Is there a way to see it on my PC as well as in VR?

**Comment by phr00t** [comment]
Glad it is working. To see it on the PC, use the mirroring preconfigure option:

https://github.com/phr00t/jMonkeyVR/blob/master/test/jmevr/TestOpenVR.java#L54
