### ISSUE TITLE
How do I obtain the VR haptic feedback controller data?

### ISSUE THREAD

**Issue by i-make-robots** [phr00t/jmonkeyengine-virtual-reality#7]
I'm holding the two controllers, one in each hand.  How do I get that data in engine as I wave them around and touch the trackpads/click buttons?

**Comment by phr00t** [comment]
Here is an example of reading the trigger button:

https://github.com/phr00t/jMonkeyVR/blob/master/test/jmevr/TestOpenVR.java#L300

I also issue a small haptic feedback pulse when doing so immediately after:

https://github.com/phr00t/jMonkeyVR/blob/master/test/jmevr/TestOpenVR.java#L304

**Comment by i-make-robots** [comment]
What about the controller position?  I want to implement a basic teleport mechanism, which means ray casting, which means location matrix.

**Comment by phr00t** [comment]
Just a few lines above the ones I pointed out above:

https://github.com/phr00t/jMonkeyVR/blob/master/test/jmevr/TestOpenVR.java#L294

Please look over the sample project, which it appears you haven't done, before opening "issues".

**Comment by i-make-robots** [comment]
I had only read the one method and the method name "getFinalObserverPosition" did not imply handles.  My bad.  Thank you!

**Comment by phr00t** [comment]
Ah, the difference is one is in VRInput (e.g. Vive wands) & the other is in VRApplication (general headset & app functions).

**Comment by i-make-robots** [comment]
VRInput.getFinalObserverRotation and VRInput.getFinalObserverPosition are returning null.  The test code says nothing about initializing VRInput, and javadoc doesn't load.  SteamVR is running and wands are active.  Hint, please?

**Comment by phr00t** [comment]
Have you tried compiling and running the test code & see if the wands are shown / updated?

**Comment by i-make-robots** [comment]
I ran it again, to be sure.  The floor and boxes are fine.  The gui cursor moves about half what it should to stay in the center of my FOV.  the skybox appears to move 2x speed.

When I switch back to my test app suddenly I'm not getting errors about unshaded.j3md and I can see the controllers, but each camera eye is about 1' apart.  some kind of scale problem?

**Comment by phr00t** [comment]
The skybox is messed up because it doesn't have an instancing-aware shader, and the test application is running in VR-instancing mode. The boxes & floor are using VR-instancing-aware shaders.

What is the absolute locations of each camera?

**Comment by i-make-robots** [comment]
How do I get that information?

VRApplication.getLeftViewPort().getCamera().getLocation();?

**Comment by i-make-robots** [comment]
Instance aware shading seems to be the problem for all out of place items in the demo.  I turned it off and they're all fine.

**Comment by i-make-robots** [comment]
It was the same problem in my test.  Everything is good now.  I hope I can muddle it out from here.  Thank you!

**Comment by phr00t** [comment]
To get camera information, it should be something like this:

VRApplication.getVRViewManager().getLeftCamera()

... should have routines like getLocation(), getRotation() etc.

Ahhh, just saw your last post. Glad to hear things are better now.

**Comment by i-make-robots** [comment]
ps: yesterday jmonkeyengine wiki would not load, kept timing out.  Is that your business, or should I tell someone else?

**Comment by phr00t** [comment]
Not my business... jmonkeyengine.slack.com, perhaps.

**Comment by i-make-robots** [comment]
K.  Your help and work are inspiring and awesome.  A++ would recommend again.
