### ISSUE TITLE
missing material params?

### ISSUE THREAD

**Issue by i-make-robots** [phr00t/jmonkeyengine-virtual-reality#8]
VR instance failed on geo 'fullscene', material 'Common/MatDefs/Gui/Gui.j3md' Check material params!
VR instance failed on geo 'floor', material 'Common/MatDefs/Misc/Unshaded.j3md' Check material params!
VR instance failed on geo 'vive_controller-geom-0', material 'Common/MatDefs/Misc/Unshaded.j3md' Check material params!
VR instance failed on geo 'vive_controller-geom-0', material 'Common/MatDefs/Misc/Unshaded.j3md' Check material params!

Cannot find assets/Common/ folder in JMonkeyVR or JMonkeyEngine projects.

Am I missing something that's obvious to you?

**Comment by phr00t** [comment]
Are you purposefully trying to use VR instancing? Perhaps you should do without it for starters. If you want to use VR instancing, you need to use instancing-aware shaders.

See "How do I use VR instancing?" here: https://github.com/phr00t/jMonkeyVR/blob/master/README.md
