### ISSUE TITLE
FadeToColor

### ISSUE THREAD

**Issue by jrbudda** [phr00t/jmonkeyengine-virtual-reality#9]
More of a question: have you tried calling the FadeToColor method on the compositor successfully? I'm just trying it for the first time and it either does nothing or crashes java with an illegal access exception.

**Comment by phr00t** [comment]
I haven't tried it myself. Some native function declarations had to be tweaked to work better, like changing  FloatByReference to FloatBuffer.. not sure if FadeToColor might need a little tweaking. Haven't looked at it or tried to use it myself :-/

**Comment by jrbudda** [comment]
ok, i'll try that

**Comment by jrbudda** [comment]
Ok I think i figured it out. I'm still on 1.0.0 of openvr and had to dial the compositor function table back to version 014. In your 1.0.0 commit you incremented to 15, but there were no functions added. In the 1.0.1 commit there were functions added but the table version didn't change. I don't know why that would cause an issue since I'm fairly certain i'm calling the 1.0.0 dll's but who knows at this point.

**Comment by phr00t** [comment]
Have you tried the 1.0.2 commit?

**Comment by jrbudda** [comment]
not yet, will update for next release and report for back. for science.

**Comment by jrbudda** [comment]
works fine out of the box in 1.0.2. There's still an issue with FadeToColor where it stops... working at all but I think it's on Valve's end.
